
name: Version Build

on:
  push:
    branches: [ main ]

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: zip
      run: zip -r repo.zip *
    - name: upload
      uses: actions/upload-artifact@v2
      if: ${{ !github.head_ref }}
      with:
          name: repo
          path: repo.zip
