
name: Version Build

on:
  push:
    branches: [ main ]

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: chmod
      run: |
        chmod +x ./init.sh
    - name: init
      run: |
        ./init.sh
