
name: Version Build

on:
  push:
    branches: [ main ]

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: chmod
      run: |
        chmod +x ./init.sh
    - name: init
      run: |
        ./init.sh
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
    - uses: actions/checkout@v2
    - uses: papeloto/action-zip@v1
      with:
        files: dist/ manifest.json
        dest: result.zip
